CAST(MD5_BINARY(CONCAT(
    IFNULL(UPPER(TRIM(CAST(CUSTOMER_ID AS VARCHAR))), '^^'), '||',
    IFNULL(UPPER(TRIM(CAST(DOB AS VARCHAR))), '^^'), '||',
    IFNULL(UPPER(TRIM(CAST(PHONE AS VARCHAR))), '^^') ))
AS BINARY(16)) AS c