SELECT '1'  AS LOADDATE,
       '2'  AS CUSTOMER_ID,
       '3'  AS CUSTOMER_DOB,
       '4'  AS CUSTOMER_NAME,
       '6'  AS NATIONALITY,
       '7'  AS PHONE,
       '8'  AS TEST_COLUMN_2,
       '9'  AS TEST_COLUMN_3,
       '10' AS TEST_COLUMN_4,
       '11' AS TEST_COLUMN_5,
       '12' AS TEST_COLUMN_6,
       '13' AS TEST_COLUMN_7,
       '14' AS TEST_COLUMN_8,
       '15' AS TEST_COLUMN_9