{{ config(schema='VLT') }}

MERGE INTO DV_PROTOTYPE_DB.VLT.HUB_CUSTOMER AS hub
USING (
SELECT DISTINCT a.CUSTOMER_PK, a.CUSTOMERKEY, a.LOADDATE, a.SOURCE 
FROM DV_PROTOTYPE_DB.STG.V_STG_CUSTOMER AS a) AS stg
ON hub.CUSTOMER_PK=stg.CUSTOMER_PK
WHEN NOT MATCHED THEN INSERT (hub.CUSTOMER_PK, hub.CUSTOMERKEY, hub.LOADDATE, hub.SOURCE) 
VALUES (stg.CUSTOMER_PK, stg.CUSTOMERKEY, stg.LOADDATE, stg.SOURCE)