{{ config(schema='VLT', materialized='table', unique_key='DV_PROTOTYPE_DB.SRC_STG.V_STG_TPCH_DATA.CUSTOMER_PK',
  post_hook = 'ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.HUB_CUSTOMER ADD PRIMARY KEY (CUSTOMER_PK)') }}

SELECT DISTINCT
  stg.CUSTOMER_PK,
	stg.CUSTOMERKEY,
	stg.LOADDATE,
	stg.SOURCE
FROM (
SELECT
  a.CUSTOMER_PK,
	a.CUSTOMERKEY,
	a.LOADDATE,
	LAG(a.LOADDATE, 1) OVER(PARTITION BY a.CUSTOMER_PK ORDER BY a.LOADDATE) AS FIRST_SEEN,
	a.SOURCE
FROM DV_PROTOTYPE_DB.SRC_STG.V_STG_TPCH_DATA AS a) AS stg

{% if is_incremental() %}

  WHERE stg.FIRST_SEEN IS NULL

{% else %}

  WHERE stg.FIRST_SEEN IS NULL

{% endif %}

LIMIT 10