{{ config(schema='VLT') }}

MERGE INTO DV_PROTOTYPE_DB.VLT.HUB_NATION AS hub
USING (
SELECT DISTINCT a.NATION_PK, a.CUSTOMER_NATIONKEY, a.LOADDATE, a.SOURCE 
FROM DV_PROTOTYPE_DB.STG.V_STG_CUSTOMER AS a) AS stg
ON hub.CUSTOMER_NATIONKEY=stg.CUSTOMER_NATIONKEY
WHEN NOT MATCHED THEN INSERT (hub.NATION_PK, hub.CUSTOMER_NATIONKEY, hub.LOADDATE, hub.SOURCE) 
VALUES (stg.NATION_PK, stg.CUSTOMER_NATIONKEY, stg.LOADDATE, stg.SOURCE);