{{ config(schema='VLT', materialized='table', enabled=false) }}

MERGE INTO DV_PROTOTYPE_DB.VLT.LINK_CUSTOMER_NATION AS link
USING (
SELECT DISTINCT a.CUSTOMER_NATION_PK, a.CUSTOMER_PK, a.NATION_PK, a.LOADDATE, a.SOURCE
FROM DV_PROTOTYPE_DB.STG.V_STG_CUSTOMER AS a) AS stg
ON link.CUSTOMER_NATION_PK=stg.CUSTOMER_NATION_PK
WHEN NOT MATCHED THEN INSERT (link.CUSTOMER_NATION_PK, link.CUSTOMER_PK, link.NATION_PK, link.LOADDATE, link.SOURCE)
VALUES (stg.CUSTOMER_NATION_PK, stg.CUSTOMER_PK, stg.NATION_PK, stg.LOADDATE, stg.SOURCE);