{{ config(schema='VLT') }}

MERGE INTO DV_PROTOTYPE_DB.VLT.SAT_CUSTOMER AS sat
USING (
SELECT 
	a.HASHDIFF,
	a.CUSTOMER_PK,
	a.CUSTOMER_NAME,
	a.CUSTOMER_ADDRESS,
	a.CUSTOMER_PHONE,
	a.CUSTOMER_ACCBAL,
	a.CUSTOMER_MKTSEGMENT,
	a.CUSTOMER_COMMENT,
	a.LOADDATE,
	LEAD(a.LOADDATE, 1) OVER(PARTITION BY a.HASHDIFF ORDER BY a.LOADDATE) AS latest,
	a.SOURCE
FROM DV_PROTOTYPE_DB.STG.V_STG_CUSTOMER AS a) AS stg
ON sat.CUSTOMER_HASHDIFF=stg.HASHDIFF
WHEN NOT MATCHED AND stg.latest IS NULL THEN INSERT (
	sat.CUSTOMER_HASHDIFF, 
	sat.CUSTOMER_PK,
	sat.CUSTOMER_NAME,
	sat.CUSTOMER_ADDRESS,
	sat.CUSTOMER_PHONE,
	sat.CUSTOMER_ACCBAL,
	sat.CUSTOMER_MKTSEGMENT,
	sat.CUSTOMER_COMMENT,
	sat.LOADDATE,
	sat.SOURCE)
VALUES (
	stg.HASHDIFF,
	stg.CUSTOMER_PK,
	stg.CUSTOMER_NAME,
	stg.CUSTOMER_ADDRESS,
	stg.CUSTOMER_PHONE,
	stg.CUSTOMER_ACCBAL,
	stg.CUSTOMER_MKTSEGMENT,
	stg.CUSTOMER_COMMENT,
	stg.LOADDATE,
	stg.SOURCE);

	