{{ config(schema='VLT', materialized='incremental', enabled=true)}}

SELECT DISTINCT
	stg.CUSTOMER_HASHDIFF,
	stg.CUSTOMER_PK,
	stg.CUSTOMER_NAME,
	stg.CUSTOMER_ADDRESS,
	stg.CUSTOMER_PHONE,
	stg.CUSTOMER_ACCBAL,
	stg.CUSTOMER_MKTSEGMENT,
	stg.CUSTOMER_COMMENT,
	stg.LOADDATE,
  stg.EFFECTIVE_FROM,
	stg.SOURCE
FROM (
SELECT
	a.CUSTOMER_HASHDIFF,
	a.CUSTOMER_PK,
	a.CUSTOMER_NAME,
	a.CUSTOMER_ADDRESS,
	a.CUSTOMER_PHONE,
	a.CUSTOMER_ACCBAL,
	a.CUSTOMER_MKTSEGMENT,
	a.CUSTOMER_COMMENT,
	a.LOADDATE,
	LEAD(a.LOADDATE, 1) OVER(PARTITION BY a.CUSTOMER_HASHDIFF ORDER BY a.LOADDATE) AS LATEST,
  a.EFFECTIVE_FROM,
	a.SOURCE
FROM {{ref('v_stg_tpch_data')}} AS a) AS stg

{% if is_incremental() %}

WHERE stg.CUSTOMER_HASHDIFF NOT IN (SELECT CUSTOMER_HASHDIFF FROM {{this}}) AND stg.LATEST IS NULL

{% else %}

WHERE stg.LATEST IS NULL

{% endif %}

LIMIT 10