{{config(schema='VLT', materialized='incremental', unique_key='CUSOMER_HASHDIFF', enabled=true)}}

SELECT DISTINCT stg.CUSTOMER_HASHDIFF, stg.CUSTOMER_PK, stg.CUSTOMER_NAME, stg.CUSTOMER_PHONE, stg.LOADDATE, stg.EFFECTIVE_FROM, stg.SOURCE 
FROM (
SELECT a.CUSTOMER_HASHDIFF, a.CUSTOMER_PK, a.CUSTOMER_NAME, a.CUSTOMER_PHONE, a.LOADDATE, a.EFFECTIVE_FROM, a.SOURCE, LAG(a.LOADDATE, 1) OVER(PARTITION BY a.CUSOMER_HASHDIFF ORDER BY a.LOADDATE) AS FIRST_SEEN 
FROM {{ref('v_stg_tpch_data')}} AS a) AS stg
{% if is_incremental() %}
WHERE stg.CUSOMER_HASHDIFF NOT IN (SELECT CUSOMER_HASHDIFF FROM {{this}}) AND stg.FIRST_SEEN IS NULL
{% else %}
WHERE stg.FIRST_SEEN IS NULL
{% endif %}
LIMIT 10