{{config(materialized='view', enabled=true, schema='VLT', tags=['static', 'incremental'])}}

SELECT
  stg.CUSTOMER_NATION_REGION_PK AS NATION_REGION_PK,
  stg.CUSTOMER_NATION_PK AS NATION_PK,
  stg.CUSTOMER_NATIONKEY AS NATIONKEY,
  stg.CUSTOMER_NATION_HASHDIFF AS NATION_HASHDIFF,
  stg.CUSTOMER_NATION_NAME AS NATION_NAME,
  stg.CUSTOMER_NATION_COMMENT AS NATION_COMMENT,
  stg.CUSTOMER_REGION_PK AS REGION_PK,
  stg.CUSTOMER_REGIONKEY AS REGIONKEY,
  stg.CUSTOMER_REGION_HASHDIFF AS REGION_HASHDIFF,
  stg.CUSTOMER_REGION_NAME AS REGION_NAME,
  stg.CUSTOMER_REGION_COMMENT AS REGION_COMMENT,
  stg.LOADDATE,
  stg.EFFECTIVE_FROM,
  stg.SOURCE
FROM {{ref('v_stg_orders')}} AS stg
UNION
SELECT
  stg.LINK_SUPPLIER_NATION_REGION_PK AS NATION_REGION_PK,
  stg.SUPPLIER_NATION_KEY_PK AS NATION_PK,
  stg.SUPPLIER_NATION_KEY AS NATIONKEY,
  stg.SUPPLIER_NATION_HASHDIFF AS NATION_HASHDIFF,
  stg.SUPPLIER_NATION_NAME AS NATION_NAME,
  stg.SUPPLIER_NATION_COMMENT AS NATION_COMMENT,
  stg.SUPPLIER_REGION_KEY_PK AS REGION_PK,
  stg.SUPPLIER_REGION_KEY AS REGIONKEY,
  stg.SUPPLIER_REGION_HASHDIFF AS REGION_HASHDIFF,
  stg.SUPPLIER_REGION_NAME AS REGION_NAME,
  stg.SUPPLIER_REGION_COMMENT AS REGION_COMMENT,
  stg.LOADDATE,
  stg.EFFECTIVE_FROM,
  stg.SOURCE
FROM {{ref('v_stg_inventory')}} AS stg
