{{config(materialized='view', enabled=true,
post_hook='DROP VIEW IF EXISTS {{this}}')}}

SELECT
  stg.CUSTOMER_NATIONKEY_PK AS NATION_PK,
  stg.CUSTOMER_NATIONKEY AS NATIONKEY,
  stg.CUSTOMER_NATION_HASHDIFF AS NATION_HASHDIFF,
  stg.CUSTOMER_NATION AS NATION_NAME,
  stg.CUSTOMER_NATION_COMMENT AS NATION_COMMENT,
  stg.LOADDATE,
  LAG(stg.LOADDATE, 1) OVER(PARTITION BY stg.CUSTOMER_NATIONKEY_PK ORDER BY stg.LOADDATE) AS FIRST_SEEN,
  LEAD(stg.LOADDATE, 1) OVER(PARTITION BY stg.CUSTOMER_NATION_HASHDIFF ORDER BY stg.LOADDATE) AS LATEST,
  stg.EFFECTIVE_FROM,
  stg.SOURCE
FROM {{ref('v_stg_tpch_data')}} AS stg
UNION
SELECT
  stg.SUPPLIER_NATION_PK AS NATION_PK,
  stg.SUPPLIER_NATIONKEY AS NATIONKEY,
  stg.SUPPLIER_NATION_HASHDIFF AS NATION_HASHDIFF,
  stg.SUPPLIER_NATION_NAME AS NATION_NAME,
  stg.SUPPLIER_NATION_COMMENT AS NATION_COMMENT,
  LAG(stg.LOADDATE, 1) OVER(PARTITION BY stg.SUPPLIER_NATION_PK ORDER BY stg.LOADDATE) AS FIRST_SEEN,
  LEAD(stg.LOADDATE, 1) OVER(PARTITION BY stg.SUPPLIER_NATION_HASHDIFF ORDER BY stg.LOADDATE) AS LATEST,
  stg.LOADDATE,
  stg.EFFECTIVE_FROM,
  stg.SOURCE
FROM {{ref('v_stg_tpch_data')}} AS stg

