{{config(materialized='view', enabled=true, schema='VLT')}}

SELECT
  stg.CUSTOMER_REGION_PK AS REGION_PK,
  stg.CUSTOMER_REGIONKEY AS REGIONKEY,
  stg.CUSTOMER_REGION_HASHDIFF AS REGION_HASHDIFF,
  stg.CUSTOMER_REGION_NAME AS REGION_NAME,
  stg.CUSTOMER_REGION_COMMENT AS REGION_COMMENT,
  LAG(stg.LOADDATE, 1) OVER(PARTITION BY stg.CUSTOMER_REGION_PK ORDER BY stg.LOADDATE) AS FIRST_SEEN,
  LEAD(stg.LOADDATE, 1) OVER(PARTITION BY stg.CUSTOMER_REGION_HASHDIFF ORDER BY stg.LOADDATE) AS LATEST,
  stg.LOADDATE,
  stg.EFFECTIVE_FROM,
  stg.SOURCE
FROM {{ref('v_stg_tpch_data')}} AS stg
WHERE FIRST_SEEN IS NULL
UNION
SELECT
  stg.SUPPLIER_REGION_PK AS REGION_PK,
  stg.SUPPLIER_REGIONKEY AS REGIONKEY,
  stg.SUPPLIER_REGION_HASHDIFF AS REGION_HASHDIFF,
  stg.SUPPLIER_REGION_NAME AS REGION_NAME,
  stg.SUPPLIER_REGION_COMMENT AS REGION_COMMENT,
  LAG(stg.LOADDATE, 1) OVER(PARTITION BY stg.SUPPLIER_REGION_PK ORDER BY stg.LOADDATE) AS FIRST_SEEN,
  LEAD(stg.LOADDATE, 1) OVER(PARTITION BY stg.SUPPLIER_REGION_HASHDIFF ORDER BY stg.LOADDATE) AS LATEST,
  stg.LOADDATE,
  stg.EFFECTIVE_FROM,
  stg.SOURCE
FROM {{ref('v_stg_tpch_data')}} AS stg
WHERE FIRST_SEEN IS NULL