parameters:
  - name: platforms
    type: object
  - name: runConfig
    type: object

jobs:
  - job: 'Test'
    steps:
      - ${{ each featureGroup in parameters.runConfig }}:
          - ${{ each subGroup in featureGroup.subGroups }}:
              - script: echo '${{ subGroup }}'
