parameters:
  - name: platforms
    type: object
  - name: run_config
    type: object

jobs:
  - job: 'Test'
    steps:
      - ${{ each feature_group in parameters.run_config }}:
          - script: echo '${{ feature_group.key }}'
