parameters:
  - name: platforms
    type: object
  - name: runConfig
    type: object

jobs:
  - job: 'Test'
    steps:
      - ${{ each featureGroup in parameters.runConfig }}:
          - script: echo '${{ featureGroup.key }}'
