{% macro add_pk(table_name) %}

CASE
  WHEN (SELECT * FROM DV_PROTOTYPE_DB.INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS a
              WHERE a.CONSTRAINT_TYPE = 'PRIMARY KEY' AND a.TABLE_NAME='HUB_CUSTOMER') = 0
  THEN ADD PRIMARY KEY (CUSTOMER_PK)
  ELSE
  END

{% endmacro %}