name: 'dbtvault_bq'
config-version: 2
# Match this version to the dbtvault repo to reflect compatibility
version: '0.7.7'
require-dbt-version: [">=0.20.0", "<0.21.0"]

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  vars:
    hash: MD5
