name: 'dbtvault_bq'

version: '0.7.0'
require-dbt-version: [">=0.14.0", "<=0.18.1"]

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  vars:
    hash: MD5
