name: 'dbtvault'
version: '0.6.2'
require-dbt-version: [">=0.14.0", "<0.18.0"]

profile: 'dbtvault'

source-paths: ["models", "models_test"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  vars:
    hash: MD5