name: 'dbtvault'
version: '0.7.4'
require-dbt-version: [">=0.18.0", "<0.20.0"]
config-version: 2
profile: dbtvault

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

vars:
  hash: MD5