name: 'dbtvault'
version: '0.6'
require-dbt-version: [">=0.14.0", "<=0.17.1"]

profile: 'dev'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  vars:
    hash: MD5