{{ config(materialized='view', schema='STG', tags='static', enabled=true) }}

select
 MD5_BINARY(UPPER(TRIM(CAST(PARTKEY AS VARCHAR)))) AS PART_PK
, MD5_BINARY(UPPER(TRIM(CAST(SUPPLIERKEY AS VARCHAR)))) AS SUPPLIER_PK
, MD5_BINARY(UPPER(TRIM(CAST(SUPPLIER_NATION_KEY AS VARCHAR)))) AS SUPPLIER_NATION_KEY_PK
, MD5_BINARY(UPPER(TRIM(CAST(SUPPLIER_REGION_KEY AS VARCHAR)))) AS SUPPLIER_REGION_KEY_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(PARTKEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIERKEY AS VARCHAR))), '^^'))) AS INVENTORY_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(SUPPLIER_NATION_KEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_REGION_KEY AS VARCHAR))), '^^'))) AS LINK_SUPPLIER_NATION_REGION_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(SUPPLIERKEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_NATION_KEY AS VARCHAR))), '^^'))) AS LINK_SUPPLIER_NATION_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(AVAILQTY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_SUPPLY_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLYCOST AS VARCHAR))), '^^'))) AS INVENTORY_HASHDIFF
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(PART_BRAND AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_CONTAINER AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_MFGR AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_NAME AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_RETAILPRICE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_SIZE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PART_TYPE AS VARCHAR))), '^^'))) AS PART_HASHDIFF
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(SUPPLIER_ACCTBAL AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_ADDRESS AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_NAME AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_PHONE AS VARCHAR))), '^^'))) AS SUPPLIER_HASHDIFF
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(SUPPLIER_NATION_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_NATION_NAME AS VARCHAR))), '^^'))) AS SUPPLIER_NATION_HASHDIFF
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(SUPPLIER_REGION_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIER_REGION_NAME AS VARCHAR))), '^^'))) AS SUPPLIER_REGION_HASHDIFF
, *, {{var('date')}} AS LOADDATE, {{var('date')}} AS EFFECTIVE_FROM, 'TPCH' AS SOURCE FROM {{ref('v_src_stg_inventory')}}