{{ config(materialized='view', schema='STG', enabled=true, tags=['static', 'increment']) }}

SELECT 
	MD5_BINARY(UPPER(TRIM(CAST(a.ORDERKEY AS VARCHAR)))) AS ORDER_PK,
	MD5_BINARY(UPPER(TRIM(CAST(a.PARTKEY AS VARCHAR)))) AS PART_PK,
	MD5_BINARY(UPPER(TRIM(CAST(a.SUPPLIERKEY AS VARCHAR)))) AS SUPPLIER_PK,
	MD5_BINARY(UPPER(TRIM(CAST(a.LINENUMBER AS VARCHAR)))) AS LINEITEM_PK,
		MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.PARTKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIERKEY AS VARCHAR))), '^^'))) AS INVENTORY_PK,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.QUANTITY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.EXTENDEDPRICE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.DISCOUNT AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.TAX AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.RETURNFLAG AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.LINESTATUS AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.COMMITDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.RECEIPTDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPINSTRUCT AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPMODE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.LINE_COMMENT AS VARCHAR))), '^^'))) AS LINEITEM_HASHDIFF,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.LINENUMBER AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDERKEY AS VARCHAR))), '^^'))) AS LINEITEM_ORDER_PK,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.ORDERSTATUS AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.TOTALPRICE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDERDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDERPRIORITY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CLERK AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPPRIORITY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDER_COMMENT AS VARCHAR))), '^^'))) AS ORDER_HASHDIFF,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.ORDERKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMERKEY AS VARCHAR))), '^^'))) AS ORDER_CUSTOMER_PK,
	MD5_BINARY(UPPER(TRIM(CAST(a.CUSTOMERKEY AS VARCHAR)))) AS CUSTOMER_PK,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMERKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATIONKEY AS VARCHAR))), '^^'))) AS CUSTOMERKEY_NATION_PK,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NAME AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_ADDRESS AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_PHONE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_ACCBAL AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_MKTSEGMENT AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_COMMENT AS VARCHAR))), '^^'))) AS CUSTOMER_HASHDIFF,
	MD5_BINARY(UPPER(TRIM(CAST(a.CUSTOMER_NATIONKEY AS VARCHAR)))) AS CUSTOMER_NATIONKEY_PK,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATION AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATION_COMMENT AS VARCHAR))), '^^'))) AS CUSTOMER_NATION_HASHDIFF,
	MD5_BINARY(UPPER(TRIM(CAST(a.CUSTOMER_REGIONKEY AS VARCHAR)))) AS CUSTOMER_REGION_PK,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATIONKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_REGIONKEY AS VARCHAR))), '^^'))) AS CUSTOMER_NATION_REGION_PK,
	MD5_BINARY(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_REGION_NAME AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_REGION_COMMENT AS VARCHAR))), '^^'))) AS CUSTOMER_REGION_HASHDIFF,
	a.*,
	{{var("date")}} AS LOADDATE,
	{{var("date")}} AS EFFECTIVE_FROM,
	'TPCH' AS SOURCE
FROM {{ref('source_system')}} AS a
ORDER BY a.ORDERKEY
limit 20


