{{config(
	schema='STG',
	materialized='view',
	enabled=false
)}}

SELECT 
	MD5(UPPER(TRIM(CAST(a.ORDERKEY AS VARCHAR)))) AS ORDER_PK,
	MD5(UPPER(TRIM(CAST(a.PARTKEY AS VARCHAR)))) AS PART_PK,
	MD5(UPPER(TRIM(CAST(a.SUPPLIERKEY AS VARCHAR)))) AS SUPPLIER_PK,
	MD5(UPPER(TRIM(CAST(a.LINENUMBER AS VARCHAR)))) AS LINEITEM_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.QUANTITY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.EXTENDEDPRICE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.DISCOUNT AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.TAX AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.RETURNFLAG AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.LINESTATUS AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.COMMITDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.RECEIPTDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPINSTRUCT AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPMODE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.LINE_COMMENT AS VARCHAR))), '^^'))) AS LINEITEM_HASHDIFF,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.LINENUMBER AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDERKEY AS VARCHAR))), '^^'))) AS LINEITEM_ORDER_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.ORDERSTATUS AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.TOTALPRICE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDERDATE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDERPRIORITY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CLERK AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SHIPPRIORITY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.ORDER_COMMENT AS VARCHAR))), '^^'))) AS ORDER_HASHDIFF,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.ORDERKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMERKEY AS VARCHAR))), '^^'))) AS ORDER_CUSTOMER_PK,
	MD5(UPPER(TRIM(CAST(a.CUSTOMERKEY AS VARCHAR)))) AS CUSTOMER_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMERKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATIONKEY AS VARCHAR))), '^^'))) AS CUSTOMER_NATION_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NAME AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_ADDRESS AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_PHONE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_ACCBAL AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_MKTSEGMENT AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_COMMENT AS VARCHAR))), '^^'))) AS CUSTOMER_HASHDIFF,
	MD5(UPPER(TRIM(CAST(a.CUSTOMER_NATIONKEY AS VARCHAR)))) AS NATION_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATION AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATION_COMMENT AS VARCHAR))), '^^'))) AS NATION_HASHDIFF,
	MD5(UPPER(TRIM(CAST(a.CUSTOMER_REGIONKEY AS VARCHAR)))) AS REGION_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_NATIONKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_REGIONKEY AS VARCHAR))), '^^'))) AS NATION_REGION_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_REGION_NAME AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.CUSTOMER_REGION_COMMENT AS VARCHAR))), '^^'))) AS REGION_HASHDIFF,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.AVAILQTY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLYCOST AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PARTSUPPLY_COMMENT AS VARCHAR))), '^^'))) AS PARTSUPP_HASHDIFF,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.LINENUMBER AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PARTKEY AS VARCHAR))), '^^'))) AS LINEITEM_PARTSUPP_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.PART_NAME AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.MFGR AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PART_BRAND AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PART_TYPE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PART_SIZE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PART_CONTAINER AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PART_RETAILPRICE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.PART_COMMENT AS VARCHAR))), '^^'))) AS PART_HASHDIFF,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.PARTKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIERKEY AS VARCHAR))), '^^'))) AS PART_SUPPLIER_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIERKEY AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIER_NATIONKEY AS VARCHAR))), '^^'))) AS SUPPLIER_NATION_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIER_NAME AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIER_ADDRESS AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIER_PHONE AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIER_ACCTBAL AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIER_COMMENT AS VARCHAR))), '^^'))) AS SUPPLIER_HASHDIFF,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(a.LINENUMBER AS VARCHAR))), '^^'), '||',
		IFNULL(UPPER(TRIM(CAST(a.SUPPLIERKEY AS VARCHAR))), '^^'))) AS LINEITEM_SUPPLIER_PK,
	a.*,
	CAST('1993-01-01' AS DATE) AS LOADDATE,
  CAST('1993-01-01' AS DATE) AS EFFECTIVE_FROM,
	'TPCH' AS SOURCE,
  a.ORDERKEY AS o_key
FROM DV_PROTOTYPE_DB.SRC.SOURCE_SYSTEM AS a
ORDER BY a.ORDERKEY
LIMIT 10

