{{ config(materialized='view', schema='STG', tags=['static', 'incremental'], enabled=true) }}

select
 MD5_BINARY(UPPER(TRIM(CAST(ORDERKEY AS VARCHAR)))) AS ORDER_PK
, MD5_BINARY(UPPER(TRIM(CAST(PARTKEY AS VARCHAR)))) AS PART_PK
, MD5_BINARY(UPPER(TRIM(CAST(SUPPLIERKEY AS VARCHAR)))) AS SUPPLIER_PK
, MD5_BINARY(UPPER(TRIM(CAST(LINENUMBER AS VARCHAR)))) AS LINEITEM_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(PARTKEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIERKEY AS VARCHAR))), '^^'))) AS INVENTORY_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(LINENUMBER AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(PARTKEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SUPPLIERKEY AS VARCHAR))), '^^'))) AS INVENTORY_ALLOCATION_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(COMMITDATE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(DISCOUNT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(EXTENDEDPRICE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(LINESTATUS AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(LINE_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(QUANTITY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(RECEIPTDATE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(RETURNFLAG AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SHIPDATE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SHIPINSTRUCT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SHIPMODE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(TAX AS VARCHAR))), '^^'))) AS LINEITEM_HASHDIFF
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(LINENUMBER AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(ORDERKEY AS VARCHAR))), '^^'))) AS LINEITEM_ORDER_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(CLERK AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(ORDERDATE AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(ORDERPRIORITY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(ORDERSTATUS AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(ORDER_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(SHIPPRIORITY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(TOTALPRICE AS VARCHAR))), '^^'))) AS ORDER_HASHDIFF
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(CUSTOMERKEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(ORDERKEY AS VARCHAR))), '^^'))) AS ORDER_CUSTOMER_PK
, MD5_BINARY(UPPER(TRIM(CAST(CUSTOMERKEY AS VARCHAR)))) AS CUSTOMER_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(CUSTOMERKEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_NATIONKEY AS VARCHAR))), '^^'))) AS LINK_CUSTOMER_NATION_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(CUSTOMER_ACCBAL AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_ADDRESS AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_MKTSEGMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_NAME AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_PHONE AS VARCHAR))), '^^'))) AS CUSTOMER_HASHDIFF
, MD5_BINARY(UPPER(TRIM(CAST(CUSTOMER_NATIONKEY AS VARCHAR)))) AS CUSTOMER_NATION_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(CUSTOMER_NATION_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_NATION_NAME AS VARCHAR))), '^^'))) AS CUSTOMER_NATION_HASHDIFF
, MD5_BINARY(UPPER(TRIM(CAST(CUSTOMER_REGIONKEY AS VARCHAR)))) AS CUSTOMER_REGION_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(CUSTOMER_NATIONKEY AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_REGIONKEY AS VARCHAR))), '^^'))) AS CUSTOMER_NATION_REGION_PK
, MD5_BINARY(CONCAT(IFNULL(UPPER(TRIM(CAST(CUSTOMER_REGION_COMMENT AS VARCHAR))), '^^'), '||', IFNULL(UPPER(TRIM(CAST(CUSTOMER_REGION_NAME AS VARCHAR))), '^^'))) AS CUSTOMER_REGION_HASHDIFF
, *, {{var('date')}} AS LOADDATE, {{var('date')}} AS EFFECTIVE_FROM, 'TPCH' AS SOURCE FROM {{ref('v_src_stg_orders')}}