MERGE INTO DV_PROTOTYPE_DB.TEST_VLT.LINK_CUSTOMER_NATION AS link
USING (
SELECT DISTINCT
	a.CUSTOMER_NATION_PK,
  a.CUSTOMER_PK,
  a.NATION_PK,
	a.CUSTOMERKEY,
  a.LOADDATE,
	LAG(a.LOADDATE, 1) OVER(PARTITION BY a.CUSTOMER_NATION_PK ORDER BY a.LOADDATE) AS first_seen,
	a.SOURCE
FROM DV_PROTOTYPE_DB.TEST_STG.STG_CUSTOMER AS a ORDER BY a.CUSTOMERKEY) AS stg
ON link.CUSTOMER_NATION_PK=stg.CUSTOMER_NATION_PK
WHEN NOT MATCHED AND stg.first_seen IS NULL THEN INSERT (
	link.CUSTOMER_NATION_PK,
	link.CUSTOMER_PK,
  link.NATION_PK,
	link.LOADDATE,
	link.SOURCE)
VALUES (
	stg.CUSTOMER_NATION_PK,
	stg.CUSTOMER_PK,
  stg.NATION_PK,
	stg.LOADDATE,
	stg.SOURCE);