MERGE INTO DV_PROTOTYPE_DB.TEST_VLT.SAT_HUB_CUSTOMER AS sat
USING (
SELECT DISTINCT
	a.HASHDIFF,
	a.CUSTOMER_PK,
	a.CUSTOMER_NAME,
	a.CUSTOMER_PHONE,
	a.LOADDATE,
	LEAD(a.LOADDATE, 1) OVER(PARTITION BY a.HASHDIFF ORDER BY a.LOADDATE) AS latest,
	a.SOURCE
FROM DV_PROTOTYPE_DB.TEST_STG.STG_CUSTOMER AS a) AS stg
ON sat.HASHDIFF=stg.HASHDIFF
WHEN NOT MATCHED AND stg.latest IS NULL THEN INSERT (
	sat.HASHDIFF,
	sat.CUSTOMER_PK,
	sat.CUSTOMER_NAME,
	sat.CUSTOMER_PHONE,
	sat.LOADDATE,
	sat.SOURCE)
VALUES (
	stg.HASHDIFF,
	stg.CUSTOMER_PK,
	stg.CUSTOMER_NAME,
	stg.CUSTOMER_PHONE,
	stg.LOADDATE,
	stg.SOURCE);

	