CREATE VIEW DV_PROTOTYPE_DB.TEST_STG.v_stg_customer AS
SELECT
	MD5(UPPER(TRIM(CAST(c.CUSTOMERKEY AS VARCHAR)))) AS CUSTOMER_PK,
	MD5(UPPER(TRIM(CAST(c.CUSTOMER_NATIONKEY AS VARCHAR)))) AS NATION_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(c.CUSTOMERKEY AS VARCHAR))), '^^'), '**',
		IFNULL(UPPER(TRIM(CAST(c.CUSTOMER_NATIONKEY AS VARCHAR))), '^^'))) AS CUSTOMER_NATION_PK,
	MD5(CONCAT(
		IFNULL(UPPER(TRIM(CAST(c.CUSTOMER_NAME AS VARCHAR))), '^^'), '**',
		IFNULL(UPPER(TRIM(CAST(c.CUSTOMER_PHONE AS VARCHAR))), '^^'))) AS HASHDIFF,
	c.CUSTOMERKEY,
	c.CUSTOMER_NAME,
	c.CUSTOMER_PHONE,
	c.CUSTOMER_NATIONKEY,
  CAST('1993-01-01' AS DATE) AS LOADDATE,
	'TPCH' AS SOURCE
FROM DV_PROTOTYPE_DB.TEST_SRC.HISTORY AS c
ORDER BY c.CUSTOMERKEY
LIMIT 10;