{%- macro prepend_generated_by() -%}

    {{- adapter.dispatch('prepend_generated_by', 'dbtvault')() -}}

{%- endmacro %}

{%- macro default__prepend_generated_by() -%}
-- Generated by ColeyDev/dbtvault. Default.
{%- endmacro -%}

{%- macro redshift__prepend_generated_by() -%}
-- Generated by ColeyDev/dbtvault. Redshift.
{%- endmacro -%}