/*
 * Copyright (c) Business Thinking Ltd. 2019-2023
 * This software includes code developed by the AutomateDV (f.k.a dbtvault) Team at Business Thinking Ltd. Trading as Datavault
 */

{%- macro prepend_generated_by() -%}
-- Generated by AutomateDV (formerly known as dbtvault)
{%- endmacro -%}