/*
 * Copyright (c) Business Thinking Ltd. 2019-2022
 * This software includes code developed by the dbtvault Team at Business Thinking Ltd. Trading as Datavault
 */

{%- macro prepend_generated_by() -%}
-- Generated by dbtvault.
{%- endmacro -%}