{#- Copyright 2019 Business Thinking LTD. trading as Datavault

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-#}
{%- macro hub(src_pk, src_nk, src_ldts, src_source,
              source) -%}

{#- {{ log('source: ' ~source, true)}} -#}

{%- if obj is iterable and source is not string -%}
    {%- set multi_source = [] -%}
    {%- for element in source -%}
        {#- {{ log('element: ' ~ref('v_stg_orders'), true)}} -#}
        {%- set _ = multi_source.append(ref(element)) -%}
    {%- endfor -%}
    {#- {{ log('multi_source: ' ~multi_source, true)}} -#}

    {#- {%- set tgt_cols = dbtvault.create_tgt_cols(src_pk=src_pk, src_nk=src_nk, src_ldts=src_ldts, src_source=src_source,
                                                  tgt_pk=src_pk, tgt_nk=src_nk, tgt_ldts=src_pk, tgt_source=src_source,
                                                  source=multi_source) -%} -#}

    {%- else -%}
    {%- set source = [ref('source')] -%}
    {#- {%- set tgt_cols = dbtvault.retrieve_tgt_cols(src_pk=src_pk, src_nk=src_nk, src_ldts=src_ldts, src_source=src_source,
                                                  tgt_pk=src_pk, tgt_nk=src_nk, tgt_ldts=src_ldts, tgt_source=src_source,
                                                  source=source) -%} -#}

{%- endif -%}

{#-
{%- set tgt_pk = tgt_cols['tgt_pk'] -%}
{%- set tgt_nk = tgt_cols['tgt_nk'] -%}
{%- set tgt_ldts = tgt_cols['tgt_ldts'] -%}
{%- set tgt_source = tgt_cols['tgt_source'] -%} -#}

{%- set is_union = dbtvault.is_union(source) -%}
-- Generated by dbtvault. Copyright 2019 Business Thinking LTD. trading as Datavault
SELECT DISTINCT {{ dbtvault.prefix([src_pk, src_nk, src_ldts, src_source], 'stg') }}
FROM (
    {{ dbtvault.create_source(src_pk, src_nk, src_ldts, src_source,
                              tgt_pk, tgt_nk, tgt_ldts, tgt_source,
                              source, is_union) }}
) AS stg
{# If incremental union or single #}
{%- if is_incremental() -%}
LEFT JOIN {{ this }} AS tgt
ON {{ dbtvault.prefix([src_pk|first], 'stg') }} = {{ dbtvault.prefix([src_pk|last], 'tgt') }}
WHERE {{ dbtvault.prefix([src_pk|last], 'tgt') }} IS NULL
{# If an incremental and union load -#}
{% if is_union -%}
AND stg.FIRST_SOURCE IS NULL
{%- endif -%}
{%- endif -%}
{# If a union base-load #}
{%- if is_union and not is_incremental() -%}
WHERE stg.FIRST_SOURCE IS NULL
{%- endif -%}
{%- endmacro -%}