{#- Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-#}
{%- macro t_link(src_pk, src_fk, src_payload, src_eff, src_ldts, src_source, source_model) -%}

    {{- adapter_macro('dbtvault.t_link', src_pk=src_pk, src_fk=src_fk, src_payload=src_payload, 
                      src_eff=src_eff, src_ldts=src_ldts, src_source=src_source, source_model=source_model) -}}

{%- endmacro %}

{%- macro default__t_link(src_pk, src_fk, src_payload, src_eff, src_ldts, src_source, source_model) -%}

{%- set source_cols = dbtvault.expand_column_list(columns=[src_pk, src_fk, src_payload, src_eff, src_ldts, src_source])-%}

-- Generated by dbtvault.
SELECT DISTINCT {{ dbtvault.prefix(source_cols, 'stg') }}
FROM (
      SELECT {{ dbtvault.prefix(source_cols, 'stg') }}
      FROM {{ ref(source_model) }} AS stg
) AS stg
{% if is_incremental() -%}
LEFT JOIN {{ this }} AS tgt
ON {{ dbtvault.prefix([src_pk], 'stg') }} = {{ dbtvault.prefix([src_pk], 'tgt') }}
WHERE {{ dbtvault.prefix([src_pk], 'tgt') }} IS NULL
{%- endif -%}
{%- endmacro -%}