-- Generated by dbtvault.
WITH STG AS (
    SELECT DISTINCT
    a.TEST_COLUMN_2, a.TEST_COLUMN_3, a.TEST_COLUMN_4, a.TEST_COLUMN_5
    FROM (
        SELECT b.*,
        ROW_NUMBER() OVER(
            PARTITION BY b.TEST_COLUMN_2
            ORDER BY b.TEST_COLUMN_4, b.TEST_COLUMN_5 ASC) 
        AS RN
        FROM DBT_VAULT.TEST.raw_source AS b
        WHERE b.TEST_COLUMN_2 <> MD5_BINARY('^^')
        AND b.TEST_COLUMN_2 <> MD5_BINARY('')
    ) AS a
    WHERE RN = 1
)

SELECT c.* FROM STG AS c