WITH STG AS (
    SELECT DISTINCT
    a.CUSTOMER_PK, a.CUSTOMER_ID, a.LOADDATE, a.RECORD_SOURCE
    FROM (
        SELECT b.*,
        ROW_NUMBER() OVER(
            PARTITION BY b.CUSTOMER_PK
            ORDER BY b.LOADDATE, b.RECORD_SOURCE ASC
        ) AS RN
        FROM DBT_VAULT.TEST.raw_source AS b
        WHERE b.CUSTOMER_PK <> MD5_BINARY('^^')
        AND b.CUSTOMER_PK <> MD5_BINARY('')
    ) AS a
    WHERE RN = 1
)

SELECT c.* FROM STG AS c