name: dbtvault
version: 0.7.7
require-dbt-version: ["0.20.0", "<0.21.0"]
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

vars:
  hash: MD5
  max_datetime: '9999-12-31 23:59:59.999'

dispatch:
  - macro_namespace: dbt_sqlserver
    search_order: ['dbtvault', 'dbt_sqlserver']