WITH source_data AS (
    SELECT a.CUSTOMER_PK, a.HASHDIFF, a.TEST_COLUMN_1, a.TEST_COLUMN_2, a.TEST_COLUMN_3, a.TEST_COLUMN_6, a.TEST_COLUMN_7, a.TEST_COLUMN_8, a.TEST_COLUMN_9, a.EFFECTIVE_FROM, a.LOAD_DATE, a.RECORD_SOURCE
    FROM [DATABASE_NAME].[SCHEMA_NAME].raw_source_sat AS a
    WHERE a.CUSTOMER_PK IS NOT NULL
),

first_record_in_set AS (
    SELECT
    sd.CUSTOMER_PK, sd.HASHDIFF, sd.TEST_COLUMN_1, sd.TEST_COLUMN_2, sd.TEST_COLUMN_3, sd.TEST_COLUMN_6, sd.TEST_COLUMN_7, sd.TEST_COLUMN_8, sd.TEST_COLUMN_9, sd.EFFECTIVE_FROM, sd.LOAD_DATE, sd.RECORD_SOURCE,
    RANK() OVER (
            PARTITION BY sd.CUSTOMER_PK
            ORDER BY sd.LOAD_DATE ASC
        ) as asc_rank
    FROM source_data as sd
    QUALIFY asc_rank = 1
),

unique_source_records AS (
    SELECT DISTINCT
        sd.CUSTOMER_PK, sd.HASHDIFF, sd.TEST_COLUMN_1, sd.TEST_COLUMN_2, sd.TEST_COLUMN_3, sd.TEST_COLUMN_6, sd.TEST_COLUMN_7, sd.TEST_COLUMN_8, sd.TEST_COLUMN_9, sd.EFFECTIVE_FROM, sd.LOAD_DATE, sd.RECORD_SOURCE
    FROM source_data as sd
    QUALIFY sd.HASHDIFF != LAG(sd.HASHDIFF) OVER (
        PARTITION BY sd.CUSTOMER_PK
        ORDER BY sd.LOAD_DATE ASC)
),

records_to_insert AS (
    SELECT frin.CUSTOMER_PK, frin.HASHDIFF, frin.TEST_COLUMN_1, frin.TEST_COLUMN_2, frin.TEST_COLUMN_3, frin.TEST_COLUMN_6, frin.TEST_COLUMN_7, frin.TEST_COLUMN_8, frin.TEST_COLUMN_9, frin.EFFECTIVE_FROM, frin.LOAD_DATE, frin.RECORD_SOURCE
    FROM first_record_in_set AS frin
    UNION
    SELECT usr.CUSTOMER_PK, usr.HASHDIFF, usr.TEST_COLUMN_1, usr.TEST_COLUMN_2, usr.TEST_COLUMN_3, usr.TEST_COLUMN_6, usr.TEST_COLUMN_7, usr.TEST_COLUMN_8, usr.TEST_COLUMN_9, usr.EFFECTIVE_FROM, usr.LOAD_DATE, usr.RECORD_SOURCE
    FROM unique_source_records as usr
)

SELECT * FROM records_to_insert