{{ config(schema='VLT') }}

CREATE TABLE DV_PROTOTYPE_DB.VLT.SAT_CUSTOMER
(
	CUSTOMER_HASHDIFF BINARY(16) PRIMARY KEY,
	CUSTOMER_PK BINARY(16) FOREIGN KEY REFERENCES DV_PROTOTYPE_DB.VLT.HUB_CUSTOMER,
	CUSTOMER_NAME VARCHAR(25),
	CUSTOMER_ADDRESS VARCHAR(40),
	CUSTOMER_PHONE VARCHAR(15),
	CUSTOMER_ACCBAL NUMBER(12,2),
	CUSTOMER_MKTSEGMENT VARCHAR(10),
	CUSTOMER_COMMENT VARCHAR(117),
    LOADDATE DATE,
    SOURCE VARCHAR(4)
);
