{{- config(materialized='incremental', schema='TEST_VLT', enabled=true, tags='feature') -}}

SELECT DISTINCT
                CAST(HASHDIFF AS BINARY(16)) AS HASHDIFF,
                CAST(CUSTOMER_PK AS BINARY(16)) AS CUSTOMER_PK,
                CAST(CUSTOMER_NAME AS VARCHAR(25)) AS CUSTOMER_NAME,
                CAST(CUSTOMER_PHONE AS VARCHAR(15)) AS CUSTOMER_PHONE,
                CAST(LOADDATE AS DATE) AS LOADDATE,
                CAST(EFFECTIVE_FROM AS DATE) AS EFFECTIVE_FROM,
                CAST(SOURCE AS VARCHAR(4)) AS SOURCE
FROM (
    SELECT
    a.HASHDIFF, a.CUSTOMER_PK, a.CUSTOMER_NAME, a.CUSTOMER_PHONE, a.LOADDATE, a.EFFECTIVE_FROM, a.SOURCE,
    LEAD(a.EFFECTIVE_FROM, 1)
    OVER(PARTITION by a.CUSTOMER_PK
    ORDER BY a.EFFECTIVE_FROM) AS LAST_SEEN
    FROM DV_PROTOTYPE_DB.SRC_TEST_STG.STG_CUSTOMER AS a
    LEFT JOIN {{ this }} AS tgt_a
    ON a.HASHDIFF = tgt_a.HASHDIFF
    AND tgt_a.HASHDIFF IS NULL
    ) as src
{% if is_incremental() -%}
WHERE src.HASHDIFF NOT IN (SELECT HASHDIFF FROM DV_PROTOTYPE_DB.SRC_TEST_VLT.test_sat_hub_customer)
AND LAST_SEEN IS NULL
{% else -%}
WHERE LAST_SEEN IS NULL
{%- endif -%}