{{- config(materialized='incremental', schema='TEST_VLT', enabled=true, tags='feature') -}}

SELECT DISTINCT
                CAST(CUSTOMER_NATION_PK AS BINARY(16)) AS CUSTOMER_NATION_PK,
                CAST(CUSTOMER_PK AS BINARY(16)) AS CUSTOMER_PK,
                CAST(NATION_PK AS BINARY(16)) AS NATION_PK,
                CAST(LOADDATE AS DATE) AS LOADDATE,
                CAST(SOURCE AS VARCHAR(4)) AS SOURCE
FROM (
    SELECT a.CUSTOMER_NATION_PK, a.CUSTOMER_PK, a.NATION_PK, a.LOADDATE, a.SOURCE
      ,LAG(a.SOURCE, 1)
      OVER(PARTITION by a.CUSTOMER_NATION_PK
      ORDER BY a.CUSTOMER_NATION_PK) AS FIRST_SOURCE
      FROM DV_PROTOTYPE_DB.SRC_TEST_STG.STG_CUSTOMER_NATION AS a
      LEFT JOIN {{ this }} AS tgt_a
      ON a.CUSTOMER_NATION_PK = tgt_a.CUSTOMER_NATION_PK
      AND tgt_a.CUSTOMER_NATION_PK IS NULL
 ) AS stg
{% if is_incremental() -%}
WHERE stg.CUSTOMER_NATION_PK NOT IN (SELECT CUSTOMER_NATION_PK FROM {{ this }})
AND FIRST_SOURCE IS NULL
{%- endif -%}
