{{- config(materialized='incremental', schema='TEST_VLT', enabled=true, tags='feature') -}}

SELECT DISTINCT
                CAST(INVENTORY_ALLOCATION_PK AS BINARY(16)) AS INVENTORY_ALLOCATION_PK,
                CAST(PART_PK AS BINARY(16)) AS PART_PK,
                CAST(SUPPLIER_PK AS BINARY(16)) AS SUPPLIER_PK,
                CAST(LINEITEM_PK AS BINARY(16)) AS LINEITEM_PK,
                CAST(LOADDATE AS DATE) AS LOADDATE,
                CAST(SOURCE AS VARCHAR(4)) AS SOURCE
 FROM (
    SELECT INVENTORY_ALLOCATION_PK, PART_PK, SUPPLIER_PK, LINEITEM_PK, LOADDATE, SOURCE,
           LAG(SOURCE, 1)
           OVER(PARTITION by INVENTORY_ALLOCATION_PK
           ORDER BY INVENTORY_ALLOCATION_PK) AS FIRST_SOURCE
    FROM (SELECT a.INVENTORY_ALLOCATION_PK, a.PART_PK, a.SUPPLIER_PK, a.LINEITEM_PK, a.LOADDATE, a.SOURCE
        FROM DV_PROTOTYPE_DB.SRC_TEST_STG.STG_LINEITEM AS a
        {% if is_incremental() -%}
        LEFT JOIN {{ this }} AS tgt_a
        ON a.INVENTORY_ALLOCATION_PK = tgt_a.INVENTORY_ALLOCATION_PK
        AND tgt_a.INVENTORY_ALLOCATION_PK IS NULL
        {%- endif %}
        UNION
        SELECT b.INVENTORY_ALLOCATION_PK, b.PART_PK, b.SUPPLIER_PK, b.LINEITEM_PK, b.LOADDATE, b.SOURCE
        FROM DV_PROTOTYPE_DB.SRC_TEST_STG.STG_PARTS AS b
        {% if is_incremental() -%}
        LEFT JOIN {{ this }} AS tgt_b
        ON b.INVENTORY_ALLOCATION_PK = tgt_b.INVENTORY_ALLOCATION_PK
        AND tgt_b.INVENTORY_ALLOCATION_PK IS NULL
        {%- endif %}
        UNION
        SELECT c.INVENTORY_ALLOCATION_PK, c.PART_PK, c.SUPPLIER_PK, c.LINEITEM_PK, c.LOADDATE, c.SOURCE
        FROM DV_PROTOTYPE_DB.SRC_TEST_STG.STG_SUPPLIER AS c
        {% if is_incremental() -%}
        LEFT JOIN {{ this }} AS tgt_c
        ON c.INVENTORY_ALLOCATION_PK = tgt_c.INVENTORY_ALLOCATION_PK
        AND tgt_c.INVENTORY_ALLOCATION_PK IS NULL
        {%- endif %}
        )
 AS b)
AS stg
{% if is_incremental() -%}
WHERE stg.INVENTORY_ALLOCATION_PK NOT IN (SELECT INVENTORY_ALLOCATION_PK FROM {{ this }})
AND FIRST_SOURCE IS NULL
{% else -%}
WHERE FIRST_SOURCE IS NULL
{%- endif -%}