{{config(materialized='incremental', schema='test_vlt', enabled=true, tags='feature')}}

SELECT
                CAST(CUSTOMER_PK AS BINARY(16)) AS CUSTOMER_PK,
                CAST(CUSTOMERKEY AS NUMBER(38,0)) AS CUSTOMERKEY,
                CAST(SOURCE AS VARCHAR(4)) AS SOURCE,
                CAST(LOADDATE AS DATE) AS LOADDATE
 FROM (
  SELECT DISTINCT CUSTOMER_PK, CUSTOMERKEY, SOURCE, LOADDATE
  FROM
    (SELECT a.CUSTOMER_PK, a.CUSTOMERKEY, a.SOURCE, a.LOADDATE
    FROM DV_PROTOTYPE_DB.SRC_TEST_STG.STG_CUSTOMER AS a
    )
 AS b)
AS stg
WHERE stg.CUSTOMER_PK NOT IN (SELECT CUSTOMER_PK FROM {{ this }})