"CUSTOMER_ID" AS "CUSTOMER_ID_ORIGINAL",
    IFNULL("CUSTOMER_ID", '-1') AS "CUSTOMER_ID",
"ORDER_REF" AS "ORDER_REF_ORIGINAL",
    IFNULL("ORDER_REF", '-1') AS "ORDER_REF",
"CUSTOMER_REF" AS "CUSTOMER_REF_ORIGINAL",
    IFNULL("CUSTOMER_REF", '-2') AS "CUSTOMER_REF",
"ORDER_LINE" AS "ORDER_LINE_ORIGINAL",
    IFNULL("ORDER_LINE", '-2') AS "ORDER_LINE"