version: 2

sources:
  - name: test_unit
    database: "{{ env_var('SNOWFLAKE_DB_DATABASE') }}"
    schema: "{{- target.schema -}}_{{ env_var('SNOWFLAKE_DB_USER') }}{{ '_' ~ env_var('CIRCLE_BRANCH', '') | replace('-','_') | replace('.','_') | replace('/','_') if env_var('CIRCLE_BRANCH', '') }}{{ '_' ~ env_var('CIRCLE_JOB', '') if env_var('CIRCLE_JOB', '') }}{{ '_' ~ env_var('CIRCLE_NODE_INDEX', '') if env_var('CIRCLE_NODE_INDEX', '') }}"
    tables:
      - name: source
        identifier: raw_source_table