{{
	config(
		materialized='incremental',
		unique_key=''
	)
}}

SELECT 
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_ORDERKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_PARTKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SUPPKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_LINENUMBER,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_QUANTITY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_EXTENDEDPRICE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_DISCOUNT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_TAX,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_RETURNFLAG,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_LINESTATUS,
	CASE WHEN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SHIPDATE > '1993-01-01' THEN NULL ELSE SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SHIPDATE END AS L_SHIPDATE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_COMMITDATE,
	CASE WHEN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_RECEIPTDATE > '1993-01-01' THEN NULL ELSE SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_RECEIPTDATE END AS L_RECEIPTDATE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SHIPINSTRUCT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SHIPMODE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_CUSTKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERSTATUS,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_TOTALPRICE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERDATE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERPRIORITY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_CLERK,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_SHIPPRIORITY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_CUSTKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_NAME,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_ADDRESS,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_NATIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_PHONE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_ACCTBAL,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_MKTSEGMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_NATIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_NAME,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_REGIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_REGIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_NAME,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_PARTKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_SUPPKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_AVAILQTY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_SUPPLYCOST,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_PARTKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_NAME,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_MFGR,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_BRAND,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_TYPE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_SIZE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_CONTAINER,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_RETAILPRICE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_SUPPKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_NAME,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_ADDRESS,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_NATIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_PHONE,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_ACCTBAL,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_COMMENT,
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_NATIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_NAME,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_REGIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_COMMENT,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_REGIONKEY,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_NAME,
	SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_ORDERKEY = SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERKEY = SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_CUSTKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_NATIONKEY = SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_NATIONKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_REGIONKEY = SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_REGIONKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_PARTKEY = SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_PARTKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_PARTKEY = SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_PARTKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SUPPKEY = SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_SUPPKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION AS N ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_NATIONKEY = N.N_NATIONKEY
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION AS R ON SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_REGIONKEY = R.R_REGIONKEY

{% if is_incremental() %}

	WHERE SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERDATE <= (SELECT DATE_ADD(MAX(SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS.O_ORDERDATE), INTERVAL 1 DAY) FROM {{this}})

{% endif %}