ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.HUB_CUSTOMER
ADD PRIMARY KEY (CUSTOMER_PK);

ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.SAT_HUB_CUSTOMER
ADD PRIMARY KEY (CUSTOMER_HASHDIFF);

ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.HUB_NATION
ADD PRIMARY KEY (NATION_PK);

ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.LINK_CUSTOMER_NATION
ADD PRIMARY KEY (CUSTOMER_NATION_PK);

ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.SAT_HUB_CUSTOMER
ADD FOREIGN KEY (CUSTOMER_PK) REFERENCES DV_PROTOTYPE_DB.SRC_VLT.HUB_CUSTOMER(CUSTOMER_PK);

ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.LINK_CUSTOMER_NATION
ADD FOREIGN KEY (NATION_PK) REFERENCES DV_PROTOTYPE_DB.SRC_VLT.HUB_NATION(NATION_PK);

ALTER TABLE DV_PROTOTYPE_DB.SRC_VLT.LINK_CUSTOMER_NATION
ADD FOREIGN KEY (CUSTOMER_PK) REFERENCES DV_PROTOTYPE_DB.SRC_VLT.HUB_CUSTOMER(CUSTOMER_PK);