{#- Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-#}
{%- macro link(src_pk, src_fk, src_ldts, src_source, source_model) -%}

    {{- adapter_macro('dbtvault.link', src_pk=src_pk, src_fk=src_fk, 
                      src_ldts=src_ldts, src_source=src_source, source_model=source_model) -}}

{%- endmacro %}

{%- macro default__link(src_pk, src_fk, src_ldts, src_source, source_model) -%}

{%- set source_cols = dbtvault.expand_column_list(columns=[src_pk, src_fk, src_ldts, src_source]) -%}
{%- set fk_cols = dbtvault.expand_column_list([src_fk]) -%}

-- Generated by dbtvault.
{{ 'WITH ' -}}

{%- if source_model is iterable and source_model is not string -%}

{%- for src in source_model -%}

STG_{{ loop.index|string }} AS (
    SELECT DISTINCT
    {{ dbtvault.prefix(source_cols, 'a') }}
    FROM (
        SELECT {{ src_pk }}
    {%- for fk in fk_cols -%}
    , {{ fk }}
    {%- endfor -%}
    , {{ src_ldts }}, {{ src_source }},
        ROW_NUMBER() OVER(
            PARTITION BY {{ src_pk }}
            ORDER BY {{ src_ldts }} ASC
        ) AS RN
        FROM {{ ref(src) }}
    ) AS a
    WHERE RN = 1
),
{% endfor -%}

STG AS (
    SELECT DISTINCT
    {{ dbtvault.prefix(source_cols, 'b') }}
    FROM (
        SELECT *,
        ROW_NUMBER() OVER(
            PARTITION BY {{ src_pk }}
            ORDER BY {{ src_ldts }}, {{ src_source }} ASC
        ) AS RN
        FROM (
            {%- for src in source_model %}
            SELECT * FROM STG_{{ loop.index|string }}
            {%- if not loop.last %}
            UNION ALL
            {%- endif %}
            {%- endfor %}
        )
        {{ 'WHERE ' -}}
        {%- for fk in fk_cols -%}
        {{ fk }} IS NOT NULL
        {%- if not loop.last %}
        {{ 'AND ' -}}
        {%- endif -%}
        {%- endfor %}
    ) AS b
    WHERE RN = 1
)
{%- else -%}
STG AS (
    SELECT DISTINCT
    {{ dbtvault.prefix(source_cols, 'a') }}
    FROM (
        SELECT b.*,
        ROW_NUMBER() OVER(
            PARTITION BY {{ dbtvault.prefix([src_pk], 'b') }}
            ORDER BY b.{{ src_ldts }}, b.{{ src_source }} ASC
        ) AS RN
        FROM {{ ref(source_model) }} AS b
        {{ 'WHERE ' -}}
        {%- for fk in fk_cols -%}
        b.{{ fk }} IS NOT NULL
        {%- if not loop.last %}
        {{ 'AND ' -}}
        {%- endif -%}
        {%- endfor %}
    ) AS a
    WHERE RN = 1
)
{%- endif %}

SELECT c.* FROM STG AS c
{%- if is_incremental() %}
LEFT JOIN {{ this }} AS d 
ON {{ dbtvault.prefix([src_pk], 'c') }} = {{ dbtvault.prefix([src_pk], 'd') }}
WHERE {{ dbtvault.prefix([src_pk], 'd') }} IS NULL
{%- endif -%}

{%- endmacro -%}