dbtvault:
  outputs:
    snowflake:
      type: snowflake
      account: "mz89709.europe-west2.gcp"

      user: "TIM_WILSON"
      password: "FlA7Ks2t"

      role: "DBTVAULT_DEVELOPER"
      database: "DBTVAULT_DEV"
      warehouse: "DBTVAULT_TESTING"
      schema: "TEST"

      threads: 4
      client_session_keep_alive: False

    bigquery:
      type: bigquery

      method: oauth

      project: ""
      dataset: ""

      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1

    sqlserver:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: ""
      port: ""
      database: ""
      schema: ""
      user: ""
      password: ""

  target: "snowflake"