name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ vars.ADO_ORGANIZATION }}"
          ado_project: "${{ vars.ADO_PROJECT_NAME }}"
          ado_area_path: "${{ vars.ADO_AREA_PATH }}"
          ado_iteration_path: "${{ vars.ADO_ITERATION_PATH }}"
          ado_wit: ${{ (contains(github.event.issue.title, 'FEATURE') || contains(github.event.issue.title, 'DOCS')) && 'Product Backlog Item' || 'Bug' }}         
          ado_new_state: "New"
          ado_active_state: ${{ (contains(github.event.issue.title, 'FEATURE') || contains(github.event.issue.title, 'DOCS')) && 'Active' || 'Committed' }}         
          ado_close_state: ${{ (contains(github.event.issue.title, 'FEATURE') || contains(github.event.issue.title, 'DOCS')) && 'Closed' || 'Done' }}  
          ado_bypassrules: true
          log_level: 100
