SELECT '1' AS LOADDATE,
       '2' AS TEST_COLUMN_2,
       '3' AS TEST_COLUMN_3,
       '4' AS TEST_COLUMN_4,
       '5' AS TEST_COLUMN_5,
       '6' AS TEST_COLUMN_6,
       '7' AS TEST_COLUMN_7,
       '8' AS TEST_COLUMN_8,
       '9' AS TEST_COLUMN_9